### ISSUE TITLE
Crash when hosting a Forge Server with Destroy.  

### ISSUE THREAD

**Issue by SheepyShambler** [petrolpark/Destroy#106]
PFA Logs of the time of the crash were attached:

- [debug.log](https://github.com/petrolpark/Destroy/files/13879099/debug.log)
- [latest.log](https://github.com/petrolpark/Destroy/files/13879101/latest.log)

Forge version: 47.2.19
Minecraft version: 1.20.1

Error was reproduced in a brand new forge server installation.

**Comment by Plite7067** [comment]
What version of destroy are you using? If not 0.3, try using the latest one.
Edit: just seen that you are using 0.3

**Comment by tunaguler03** [comment]
I am not sure if this helps but an issue similar to this one also happens while joining to an Open-To-LAN game.
You can open a world easily without crashes but when you open to lan and someone tries to join, they join and get disconnected immediately with the error:

**Internal Excepti,on: io.netty.handler.codec.DecoderExveption:
java.lang.NullPointerException: Cannot invoke
"net.minecraftforge.registries.ForgeRegistry.getValue(int)" because
"registry" is null**

**Comment by Fixer33** [comment]
I am hosting a dedicated server. And have the exact same issue
@petrolpark I think it would be a huge deal-breaker for many people. Thank you for the mod though - you are awesome

**Comment by petrolpark** [comment]
Duplicates of #102 (fixed in 0.4) and #64 (being looked into).
