### ISSUE TITLE
ore electrolyzation is being finnicky 2 electric boogaloo

### ISSUE THREAD

**Issue by haus-jackl** [petrolpark/Destroy#122]
I have gone and fixed all of my previous mistakes but the ore still will not electrolyze. I realize this is still most likely a mistake on my part but I feel it could be a bug. The dynamo is rotating at the maximum speed. I have used a test tube to show concentrations of basin contents, (just a suggestion but I think goggles should show concentrations of contents if you sneak or something, using a test tube can be annoying in creative mode as it just removes fluid by default) The dynamo was tested rotating in both directions.

![2024-01-11_16 53 57](https://github.com/petrolpark/Destroy/assets/54426783/88f3ce2d-9493-49fe-b6a5-613bdcca7b81)
![2024-01-11_16 54 16](https://github.com/petrolpark/Destroy/assets/54426783/df703ac4-d686-41d5-a13a-61f336c14e43)

I am utterly lost as to what is going on. Also here is a screenshot of my mods list:
![image](https://github.com/petrolpark/Destroy/assets/54426783/5e02b7c5-5b37-4d01-bd2c-20cc47c8ccb6)

**Comment by BytinYarota** [comment]
I managed to recreate this.
![image](https://github.com/petrolpark/Destroy/assets/45122555/66a1fb86-f846-4292-be8f-8fd5af0bccab)
I got such a test tube of solution from the beneath showing vat, and it doesn't work with the identical device I used in the reply to the previous issue.
![image](https://github.com/petrolpark/Destroy/assets/45122555/4ace66b1-4fee-4844-8bde-2f29c3e39bee)
By the way, I suggest using an exact number to describe the leeway instead of using a vague 'approximately'.
In addition, the 'M' is used as a unit for both concentration(in test tubes) and quantity(in vats), I wonder if we could separate them to avoid confusion.

**Comment by petrolpark** [comment]
I'll relabel the electrolysis tooltip with exact values, and change the info shown with the Vat display link (technically, it does already show concentration, but with respect to the *whole Vat*. That's not very obvious though). 

Could you run `/data get block <basin coordinates>` and tell me what you get? I think in your case, you might have an iron concentration of 4.14 or something. That's not ideal as it still shows as 4.1 so you'd expact that to react.

**Comment by BytinYarota** [comment]
Here's the result of mine
![image](https://github.com/petrolpark/Destroy/assets/45122555/63f62c87-b903-4ac9-b8cf-f498a015520f)
Seems that the concentration of iron(III) is 4.127, while that of the solution I used in the previous issue was 4.089, which worked for this recipe.

**Comment by petrolpark** [comment]
I'll probably replace it with a range (e.g. "at a concentration between 3.5M and 4.5M"). As you've been very helpful with bug reports @helloworld069, if you want you can DM me on Discord (`petrolpark`) and I'll add the **Beta Tester** Badge. (You're also owed the translator Badge, if you want that).

**Comment by haus-jackl** [comment]
If you make the inequality as 3.5 and 4.545M it will stop these strange occurrences where rounding makes it feel like it’s broken :)

**Comment by petrolpark** [comment]
This has now been implemented in 0.4.
