### ISSUE TITLE
Attempting to remove all of the gas in the vat eventually leads to flickering amounts of gas in the vat

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#184]
Forge 47.2.19, Destroy 0.5

https://github.com/petrolpark/Destroy/assets/75921990/22efd355-d566-42a0-9035-564f8c0bfa86

Kinda hard to describe in words, so a video is attached. After removing most of the gasses from a vat, it just flickers back and forth between an extreme low and high value of nitrogen and oxygen in the vat. The vat also displays that it is at -459.4 F, which is just a little bit cold. Also once it hits a low enough value, it just stops removing oxygen or nitrogen from the vat. 

To recreate this, drain the gas from a vat using fluid pipes and pump the gas into a fluid tank (as this makes the draining so much faster). This is not required, as any type of draining the vat will have the same effect.

**Comment by MindFaer** [comment]
If you need additional video/steps to recreate it, let me know, github only lets you add a video that is 10mb or less.

**Comment by Auseawesome** [comment]
Can confirm this, reason I made issue #182 but you've explained it better. I found a way to circumvent this issue, if you also vent some gas using a pump just leading into the atmosphere while draining some into another container, it won't happen for some reason. I think it's because pumping into atmosphere is much, much slower for some reason.

**Comment by petrolpark** [comment]
Fixed in 0.6.
