### ISSUE TITLE
CO does not produce any CO2 in the presence of H2 and copper and zinc catalysts (also mysterious heating)

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#223]
Inserting methane into a vat with nickel,copper,zinc catalysts and water causes it to form CO and H2, which should react in part with oxygen (of which there is a lot in the vat, definitely more than H2) to form CO2, and in part with H2 in the presence of the catalysts to form methanol. However, only methanol is formed.

Also, that aforementioned vat heated up a lot, reaching over 350C and dropping **extremely** slowly with no heating with only a slow trickle of methane going into it, despite being built fully of copper casing (1x1). Neither reaction should produce any heat at the moment. The rate of methane insertion is less than 0.0005mol/sec, and the vat in total contains ~45mols of various gases, ~2 of which are methanol. and it comes directly from centrifuging LPG. Not sure if this is a bug, or LPG has a temperature of 4 gazillion degrees.

**Comment by TheRedCrafter344** [comment]
Note: When trying in a different vat with the same catalysts, but this time more hydrogen than oxygen, only CO2 was produced, and no methanol.

**Comment by petrolpark** [comment]
Seems like both reactions are much too fast, causing one to dominate depending on the precise quantities of hydrogen, methane, etc. Now, carbon dioxide is the primary product, requiring you to flush your Vats of oxygen (or simply allow all the oxygen to react and form carbon dioxide) in order to get methanol, which is more realistic. The slow cooling problem should also be fixed - I think it was due to water having a heat capacity a thousand times as much as it should, making it too good at retaining heat.
