### ISSUE TITLE
Bug: Strange Pressure Interaction

### ISSUE THREAD

**Issue by SunShine214** [petrolpark/Destroy#239]
When you have a container with no gases, and a solution, pressure equals 101.0 kpa. The moment a gas is added the pressure behaves as expected. In addition, water in a vacuum should boil, not remain a solution. Are boiling points being static intended as a simplification or a performance requirement?

**Comment by petrolpark** [comment]
That's been fixed in 0.7. Vats with no gases now show as vacuums, unless they are completely full of liquid in which case they are considered to be at air pressure.

Boiling points are static - this is a simplification, as otherwise each molecule would need its own phase diagram, which is complicated to convey to users, difficult to program (and slightly more resource intensive), and unfitting with Destroy's model of all gases as ideal and phases as not existing (which will probably not change anytime soon). I'm thinking of adding events to the API such as calculations of phase for molecules, so that if a more complex add-on wanted to come along and introduce that sort of behaviour they could, but again it will probably not come to base Destroy soon (I'm an organic chemist, not a fluid dynamics physicist, and uber-accurate gas physics is not my cup of tea).
