### ISSUE TITLE
Suggestion: Mustard Gas

### ISSUE THREAD

**Issue by lemonelk** [petrolpark/Destroy#245]
Mustard gas that is made from ethylene and sulfur dichloride that makes people cough up their lungs on the floor.

**Comment by MindFaer** [comment]
Adding gases as weapons is a slippery slope, mostly because almost any pure gas, including oxygen, will cause asphyxia. The gases you can vent already have chemical properties that give you chemical poisoning, so how would it be different to hydrochloric acid gas from a gameplay standpoint? 

If anything, I would suggest a gas pellet you can fill with a gas, and then throw and it decompresses into the surrounding area and applies the associated effects of the gas.

**Comment by petrolpark** [comment]
MindFaer is right, and something like what they suggest will come along with the CBC compat (#91), and that's probably the only way something like this would be implemented. So I'm going to close this for now.
