### ISSUE TITLE
Laggy Vat

### ISSUE THREAD

**Issue by luluthepogcat** [petrolpark/Destroy#270]
your mod works fine with 4-5 mixture on the vat, but 7-8 mixture is the real problem
![Screenshot (83)](https://github.com/petrolpark/Destroy/assets/154001303/1d7855e3-d358-4edf-b880-4466eda8d109)
![Screenshot (84)](https://github.com/petrolpark/Destroy/assets/154001303/e81ba3e6-149c-4ef6-bcc1-0c8c745842f4)
(notice the internal server's ping before and after destroying the vat)

**Comment by petrolpark** [comment]
What are the exact contents of the Vat? (`/data get [vat controller's coordinates]` is the best way to see this).

**Comment by luluthepogcat** [comment]
> What are the exact contents of the Vat? (`/data get [vat controller's coordinates]` is the best way to see this).

I forgor, but im pretty sure you can replicate it by inserting 8 test tube of random mixture that reacts with eachother

**Comment by ToastbrotExe** [comment]
This bug also appears when mixing AIBN and protons, because the protons react with the AIBN and produce a lot of diffrent chemicals. (Used one test tube with Water, one with Hydrochloric Acid and two with AIBN to achive this)
![2024-02-12_18 39 21](https://github.com/petrolpark/Destroy/assets/159703972/971a4d20-82c3-4939-b123-f4151036bbd9)
![2024-02-12_18 39 41](https://github.com/petrolpark/Destroy/assets/159703972/093f832d-b0a9-4e9a-bb66-275b80715b00)
![2024-02-12_18 39 54](https://github.com/petrolpark/Destroy/assets/159703972/6c417cd9-c559-45de-8659-9264a44813bf)

**Comment by petrolpark** [comment]
This has been fixed, and is now back to 6-8 MSPT, at least on my laptop (20,000% faster). Basically, because some Molecules were being added and then removed from the Mixture very quickly (because they instantly react), it was refreshing the possible Reactions the Mixture could do potentially up to ten times per second, which is the most resource-intensive thing the chemistry simulation does.
