### ISSUE TITLE
Bug: JEI shows inapplicable generic reactions

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#273]
Cyanide addition is listed as a way to make non-carbonyl nitriles, i.e. adiponitrile. I'm guessing this is because it shows for all nitriles.

**Comment by petrolpark** [comment]
Upcoming generic reactions will feature ways to easily convert cyanohydrins to nitriles, so this won't be changed. The generic reactions shown in JEI are not necessarily intended to be absolutely prescriptive, but just give ideas of what's possible (like how Create's Ponders show the most basic features of its blocks, rather than telling you exactly how to make an iron farm).
