### ISSUE TITLE
Graduated Cylinder, temperature/pressure redstone interaction, freeze ray

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#324]
I feel like compounds such as ammonia and hydrogen are insanelly usefull for all kinds of reactions, and their synthesis also creates bleach, bases and acids. The drawback is the labor intensive process, which, even if all the vats and basins are linked with pipes, a player still needs to be present to control reaction rates or to add specific amounts of reagents (less than 200 mB with the test tube). So, a few sugestions are:

Making the spout interact with test tubes, making it a easier way to fill lots of test tubes for chemical transportation to another factory far away.

A graduated cylinder or device of some kind, as a way to measure exact chemical amounts with more precision than just test tubes, or distiling certain solutions.

Pressure reader, a device that acts like the threshold switch, wich could be set to give a redstone signal at certain pressures, awesome for not  blowing vats up or removing all gases from a vat.

Insulation, to achieve higher or lower temperatures in a vat, making it possible to separate individual components from air and even liquify methane and ethylene.

Cold distilation to separate liquid gases that boil below room temperature, acting just like bubble caps, but instead of blaze burners below, the refrigestraytor, also nice for air separation ( maybe even obtaining dry ice from air as a CO2 source, wich could be used for a freeze gun).

Now for something more fun, based of the Create stuff and additions flamethrower, a freeze gun, a device that can freeze all entities in place for a short period of time and aplies soft snow effects. It's "fuel" could be any refrigerant as well as any cold item, like blue ice or dry ice.

**Comment by petrolpark** [comment]
Automation is a big priority, so a lot of this stuff is planned in some form.

> Making the spout interact with test tubes, making it a easier way to fill lots of test tubes for chemical transportation to another factory far away.

If this doesn't work, that is a bug. What's in the Mixture that's not being added? For transportation of Mixtures the best way is trains though, that's why test tubes have an intentionally small capacity and part of why they don't stack.

Likelihood: 🟢 should already be working...

> A graduated cylinder or device of some kind, as a way to measure exact chemical amounts with more precision than just test tubes, or distiling certain solutions.

This is a very good idea - I suppose fine volume control is something Destroy lacks while being an important part of actual chemistry. I'll have a think about how this would best be implemented.

Likelihood: 🟢 likely

> Pressure reader, a device that acts like the threshold switch, wich could be set to give a redstone signal at certain pressures, awesome for not blowing vats up or removing all gases from a vat.

This is planned, just as a comparator interaction with the side of a Vat set to the barometer. Same with the thermometer.

Likelihood: 🟢 definite

> Insulation, to achieve higher or lower temperatures in a vat, making it possible to separate individual components from air and even liquify methane and ethylene.

This can be done just by swapping the blocks used to build the Vat. There will be more options for this coming soon.

Likelihood: 🟠 not as separate insulation, but as Vat building block alternatives

> Cold distilation to separate liquid gases that boil below room temperature, acting just like bubble caps, but instead of blaze burners below, the refrigestraytor, also nice for air separation ( maybe even obtaining dry ice from air as a CO2 source, wich could be used for a freeze gun).

This probably won't be a feature of the Bubble Cap, as it doesn't make physical sense for the temperature gradient to be inverted. It is possible with a Vat. Bubble Caps are kind of like the easier but more limited option for distillation, with finer control possible with a Vat. Of course this will become easier with the upcoming automation possibilities.

Likelihood: 🔴unlikely

**Comment by Phosgenick** [comment]
I have done some testing with the spout and it does seems to work with most solutions, don't know why it didn't when i tested it earlier with mercury to recover excess from the spout when making blacklights.  Maybe it had to do with the electrolisis volume bug, but glad it's already a feature!

**Comment by petrolpark** [comment]
Most of these have now been implemented in 1.0.
