### ISSUE TITLE
Chemical Workbench

### ISSUE THREAD

**Issue by Gfortes985** [petrolpark/Destroy#337]
I propose adding a modular table (workbench) for creating mixtures in small quantities, since now all crafting takes place at an industrial level, it would be nice if the chemical workbench could be customized, that is, add different chemical samples, flasks, test tubes, and connect them into a system for the production of some chemical compounds.

**Comment by petrolpark** [comment]
Equipment for lab scale chemistry will probably be coming (#322 test tube holder, #324 graduated cylinder, possibly a smaller reaction vessel and other glassware). I would find it weird to implement a brand new modular system when the entire Minecraft world, being made of blocks, is already modular.

**Comment by Gfortes985** [comment]
I guess I didn’t express myself clearly, I meant that we will have a certain table on which we can place equipment (modules) and in some gui connect them together with pipes or something else

**Comment by petrolpark** [comment]
That is what I mean. While it would be cool, a new system of modules will not be added when the Minecraft world can already be though of as being built of modules (individual blocks).

The issue your suggestion addresses is the need to chemistry on a small scale. Instead of a new modular system, more blocks/modules will be added to make this easier.

**Comment by petrolpark** [comment]
Closing as those things are mentioned in other issues and no point having it twice.
