### ISSUE TITLE
Adding A Reaction Calculator

### ISSUE THREAD

**Issue by donovan-maker** [petrolpark/Destroy#349]
--  Hey petrolpark
I've always had this idea, a reaction calculator item that can calculate the reaction to get from some base chemicals / liquids such as oxygen, water, and crude oil, to more complex things like trinitrotoluene (TNT) (Yes, I memorized the un-abbreviated name) or polyethylene. I want this simply because of Generic Reactions. Maybe you could also make an R-Chemical Converter / Calculator which takes the chemicals with R groups in them and tells you which chemicals match those ones. For example, the only way to make Aspirin is to use Generic Reactions. This also happens with AIBN, which is required to make polyethylene, which is required to make the Swiss Army Knife, which is required for one of the achievements, making it hard to 100% the game. (Which I love to do with games) Anyways, if you could make these two items that would be awesome, as it would help me and my friends who like to play this mod.

-- Best of wishes for your day, Donovan.

EDIT: I also just thought about datapack support for adding reactions and chemicals, that would be cool.

**Comment by petrolpark** [comment]
The end goal of the chemistry system is to create an emergent puzzle game, where its on the player to deduce what combination of molecules will join together to make the target. That's essentially what the field of Synthesis is, what I love about organic chemistry, what inspired the mod, and the reason Destroy has this complicated system of "generic" reactions rather than just a list of hardcoded recipes. This end goal isn't met yet because:

- There's no need to create anything unique. Most things have straightforward recipes that don't need you to touch the system of generic reactions - in other words, they could just be substituted for typical modded recipes and the player would not percieve them any differently.
- Other than people who already have experience in chemistry, the player is not really equipped to actually solve these puzzles. There is a steep learning curve to learn about all the possible reactions before you can start to apply them to solve puzzles, but to chemists they are already intuitive.

The first issue has been worked out and is being addressed (possibly not in 1.0, but soon after). The second issue is best addressed with some system of tutorials (which is a popular suggestion), but stems from the fact that Destroy was made entirely selfishly because I didn't find any games which provided the organic chemistry sandbox that I wanted.

To finally address your suggestion, I can see how it would make sense - Destroy has all these ingredients which it apparently doesn't tell you how to make - this seems like a pretty big flaw for a mod, like if its crafting recipes weren't included in JEI. But this is entirely by intention - Destroy at its core is a puzzle mod*. The issue is not that there are missing recipes, it is that the information that makes it clear that this is a puzzle is missing. Adding a reaction calculator is just adding something which bypasses the core puzzle of the mod (it's also extremely difficult to implement - computers can do maths, not solve problems). 

*A puzzle mod in development. Currently the groundwork is being laid. This is leaned into more in 1.0, and obviously with the upcoming changes I've mentioned above.

***

Datapack support for molecules and reactions is in the [upcoming features list](https://github.com/petrolpark/Destroy/wiki/Upcoming-Features), which you should have checked. You should also only include a single suggestion in one post.

**Comment by donovan-maker** [comment]
Actually, now that I read your response again, I see you put off the R-Chemical Converter and Generic Reactions saying 

> and the reason Destroy has this complicated system of "generic" reactions rather than just a list of hardcoded recipes.

and

> Most things have straightforward recipes that don't need you to touch the system of generic reactions

even though to progress in the mod with plastics you need, as mentioned in my opening question, AIBN, which can only be made with a Generic Reaction, as seen in [this](https://imgur.com/a/37bBu5Z) screenshot. Again, a suggested R-Chemical Converter, with hardcoded values would be nice.

**Comment by petrolpark** [comment]
It would undermine the puzzle, like if a sudoku also gave you the grid filled in. Rather than just telling you what to do, future updates will focus on teaching the player how to figure it out for themselves.

**Comment by donovan-maker** [comment]
Now that I think about it, I understand your reasoning. It is kind of a puzzle to figure it out, I'll figure it out, eventually.
