### ISSUE TITLE
Questions about translation contribution

### ISSUE THREAD

**Issue by Susul-1312** [petrolpark/Destroy#355]
While preparing a translation I have come across a few questions that i kept asking myself

- should I send pull requests for partial translations or hold off until i have translated every key?
- "translators are encouraged to come up with their own puns" does that include things like keeping alliteration when translating the patreon tiers?
- adding to the previous two questions, if i have trouble coming up with a pun on the spot, should i hold off the translation until i do or just leave it untranslated?

i apologize if these seem like unnecessary questions, i just want to make sure to do everything correctly

**Comment by petrolpark** [comment]
- Partial translations are completely fine.
- I might say that just for Badges that translations should be literal seeing as they are also referenced by name elsewhere (i.e. on my Patreon), but yes, otherwise if a "joke" only makes sense in English because it alliterates then I would recommend localising it
- I'm not sure what the convention is - I think some people leave it as a literal translation. In accordance with the first question leaving it is also fine.

Not unnecessary at all! There's no pressure, and I thank you from the bottom of my heart for any help with translation.
