### ISSUE TITLE
Pollution visual effects require a world reload to appear

### ISSUE THREAD

**Issue by Phanastrae** [petrolpark/Destroy#36]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

The visual effects of pollution (ie smog's brown grass and thick brown fog) do not immediately appear after using the /pollution command, and require leaving and rejoining the world to show up.

Steps to reproduce:
1) Create new world
2) Run /pollution SMOG set 65536
- Visual changes (fog and grass/foliage color) do not occur.
3) Leave and rejoin world
- Visual changes are now present

**Comment by Phanastrae** [comment]
This also seems to apply to swapping between dimensions.

1. Create new world, add smog, relog to make visual effects appear
2. Go to the End
The end fog will now be brown
3. Leave and rejoin world whilst still in end
The end fog will no longer be brown
4. Return to Overworld
The Overworld grass will be green and fog will not be brown
5. Leave and Rejoin
Overworld pollution effects are now visible again

**Comment by petrolpark** [comment]
It needing a reload is intentional, as in testing it seemed that Minecraft block colors are batched in chunks. It was either don't require a reload, or have drastic changes from green to brown at chunk boundaries. The smog in the overworld affecting the end sky color is definitely a bug though, and will be investigated.

**Comment by petrolpark** [comment]
Fixed in 0.3.
