### ISSUE TITLE
Making the aging barrel work like the basin and a few inprovements

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#361]
II have been trying to automate every base chemical from renewable sources, and now i was focusing on ethanol production> I have been encountering a few problems working with the aging barrel and so there are a few sujestions i'd like to make.

- When adding wheat and yeast to the basin, i have encoutered a problem: the aging barrel only accepts two items at a time, so when wheat is added together with yeast, if there are two of the same components, the barrel just hold them and don't accept the other. It would be very helpful if the barrel worked similarly to the basin ( only accepts 16 of the same item, but other itens can be added together without the other 16 affecting), but only accepting only one of each.

- If the barrel could reach 100% and open alone instead of manually having to open every time in order to remove the alcohol mix (deployers maybe could be used, but yeah)

Phosgenick

**Comment by petrolpark** [comment]
The bug where it has to be opened before pumping things out is fixed in 1.0.

I've obtained permission from the creator of Create: Diesel Generators to use the idea of their Basin Lid if wanted, so that may end up being what happens (the way it would be implemented, Destroy's Basin Lid would be disabled if CDG is installed). This would mean the Aging Barrel was removed and replaced.

**Comment by petrolpark** [comment]
I don't think a sealed basin is necessary when a Vat can be used instead, so that idea will likely not go ahead.
