### ISSUE TITLE
Petrol's Parts is incompatible with the 0.1.0 snapshots of Destroy

### ISSUE THREAD

**Issue by Cvdusey** [petrolpark/Destroy#451]
**Describe the bug**

The current 0.1.0 snapshot versions of Destroy are not compatible with Petrol's Parts

**To Reproduce**

Install the latest version of Petrol's Parts and a Destroy 0.1.0 snapshot.

**Expected Behavior**

Petrol's Parts recognizes the 0.1.0  Snapshots as being version 0.1.0 or above.

**System Information**

 - Create version 0.5.1.h
 (I have over 300 other mods installed, so I can't list them all here)

**Comment by Daxturus** [comment]
I am also seeing this issue. Petrol's Parts seems to require Destroy version 0.1.0, and that version only. The current mod beta version is 0.1.0-snapshot-5; this is _technically_ not the same as Version 0.1.0.

I must ask, though: why have a Destroy dependency _at all_ for the Petrol's Parts?

If I am not mistaken, the intent for moving Petrol's Parts out of Destroy in the first place was so that Destroy was _not_ required. From the Curseforge page for Petrol's Parts: (https://www.curseforge.com/minecraft/mc-mods/petrols-parts)

> The kinetic components were ported from [Destroy](https://www.curseforge.com/minecraft/mc-mods/create-destroy) into this separate mod so you don't have to deal with the parts of Destroy I actually spent time on.

If something added by Petrol's Parts only exists for use with Destroy, then either Petrol's Parts should just selectively register it when a compatible Destroy version is found, or it should just be moved to Destroy itself. For any other part that doesn't require Destroy, the crafting recipes could/should just require vanilla Minecraft or Create materials if no compatible Destroy version is loaded. 

The easiest fix for this, I think, is to just remove the Destroy dependency for Petrol's Parts in favor of a Petrolpark's Library dependency, and change any recipes that might require Destroy materials.

**Comment by Mo1eculeMan** [comment]
If I had to guess, 0.1.0 was put not as a dependency but to ensure that Destroy 0.0.8 and Petrol's Parts were never mixed, and so Petrol's Parts will only accept 0.1.0 (the next release) and onwards. The snapshots were not factored into this release restriction.

**Comment by CDWimmer** [comment]
You can modify the requirements set out in Petrol's Parts' `petrolsparts-1.20.1-1.0.3.jar\META-INF\mods.toml` to remove the Destroy requirement, if you want to test it out.

**Comment by petrolpark** [comment]
> If I had to guess, 0.1.0 was put not as a dependency but to ensure that Destroy 0.0.8 and Petrol's Parts were never mixed, and so Petrol's Parts will only accept 0.1.0 (the next release) and onwards. The snapshots were not factored into this release restriction.

It is this. The 0.1.0 snapshots are experimental anyway; once it releases fully it will work fine.
