### ISSUE TITLE
smart pipes should be able to pull specific chemicals out of fluid containers (e.g. vats, basins, fluid tanks) by putting something such as a vial of the specified chemical as the filter

### ISSUE THREAD

**Issue by NthPhantom10** [petrolpark/Destroy#467]
say you had a mixture of a bunch of different chemicals in a vat, but wanted one specific one. well, you could put a smart pipe on the vat and then add vial of the chemical you want to draw out on the filter section.

it makes manufacturing slightly more probable, but it is also balanced because you have to synthesize and put the chemical in a vial beforehand.

~NthPhantom10

**Comment by Mo1eculeMan** [comment]
This is both difficult to do from a programming standpoint, because Destroy's mixtures are a single Forge fluid with NBT data applied, and likely not in the intended spirit of the mod - no such thing exists in practicality. To obtain a specific chemical out of the vat, consider fractional distillation via heating/cooling, centrifuging, or reacting other chemicals to condense or sequester them.
