### ISSUE TITLE
game crashes while trying render armor in ponder

### ISSUE THREAD

**Issue by h0bbayt** [petrolpark/Destroy#520]
while ponder a disenchanter from create: enchantment industry game just crashed. Without destroy, but with petrolpark library game  don't crashes. Tested only in singleplayer, will test in multiplayer soon.
(tryed render diamond chestplate)

create 0.5.1h, destroy snapshot 10, petrolpark 1.0.6

[crash-2024-10-16_23.21.46-client.txt](https://github.com/user-attachments/files/17402546/crash-2024-10-16_23.21.46-client.txt)

**Comment by h0bbayt** [comment]
tryed to fix https://github.com/petrolpark/Destroy/pull/522 , now it don't crushes

**Comment by Explode007** [comment]
The crash also happens when they are placed on machines, not sure if this fixes that. I have thrown chainmail pieces on blasting and it crashes the client with this exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientLevel.m_9598_()" because "level" is null
	at com.petrolpark.destroy.client.model.overrides.UniversalArmorTrimItemOverrides.m_173464
